w3c/pub-manifest

common/js/pub.js
experiments/audiobook/flatland-canonical.json
experiments/audiobook/flatland.json
experiments/audiobook/toc-as-json.json
experiments/separate_manifest/mobydick-simple.jsonld
experiments/separate_manifest/mobydick.jsonld
experiments/w3c_rec/full_version.html
experiments/w3c_rec/simple-canonical.jsonld
experiments/w3c_rec/simple_version.html
index.html
schema/publication.schema.json

This PR addresses the spec issues raised in #1 and #2 by switching /wp-context to /pub-context
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/17.html" title="Last updated on Aug 7, 2019, 4:21 PM UTC (c747106)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/17/c1c1d87...c747106.html" title="Last updated on Aug 7, 2019, 4:21 PM UTC (c747106)">Diff</a>

switch wp-context to pub-context

---

index.html

This PR is a start on addressing #5. It lists the two required properties (title and reading order) and indicates that all others are optional, but priority is also dictated by specific implementations.
Interestingly, the following is the minimum valid manifest, as the "required" properties are both compiled when not set:
```
{
"@context" : ["https://schema.org", "https://www.w3.org/ns/wp-context"],
"type"     : "CreativeWork"
}
```
I'm thinking it might be worth listing context and type as required properties, even though we didn't before, rather than assume them as part of a default configuration.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/18.html" title="Last updated on Aug 7, 2019, 8:01 PM UTC (4be22d2)">Preview</a> | <a …

Add requirements section to manifest definition

---

index.html

This PR addresses #6 by simply referring to the document that references the manifest as... the document that references the manifest.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/19.html" title="Last updated on Aug 7, 2019, 6:45 PM UTC (e3f3e8a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/19/c1c1d87...e3f3e8a.html" title="Last updated on Aug 7, 2019, 6:45 PM UTC (e3f3e8a)">Diff</a>

Generalize references to the primary entry page

---

index.html

This PR fixes #25 by moving the check of `type` to the post-processing steps. If the value is not set, "CreativeWork" is used and a warning is issued.
(It also fixes a minor bug with the title where the wording suggests to issue a warning and generate a title when the value is non empty.)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/27.html" title="Last updated on Aug 9, 2019, 2:19 PM UTC (27ea111)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/27/b733e29...27ea111.html" title="Last updated on Aug 9, 2019, 2:19 PM UTC (27ea111)">Diff</a>

Make lack of type a warning

---

index.html

Opening this PR as I noticed the manifest still seems closely tied to the PEP and linking to a manifest. To make things more (obviously) flexible for implementations of the manifest, it includes the following changes:
- renames "manifest association" to "manifest discovery" and adds section that other discovery methods than linking/embedding are allowed;
- adds to base url calculation that if another method is used, the format has to define the rules
- clarifies that html document input to lifecycle steps may not always be set
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/26.html" title="Last updated on Aug 9, 2019, 4:54 PM UTC (81c657f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/26/b733e29...81c657f.html" title="Last updated on …

Clarify manifest discovery

---

index.html

This PR addresses #7 by removing the prose and lifecycle steps that allowed inheritance of language and direction from a parent script tag.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/20.html" title="Last updated on Aug 8, 2019, 10:55 AM UTC (dd06a39)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/20/b733e29...dd06a39.html" title="Last updated on Aug 8, 2019, 10:55 AM UTC (dd06a39)">Diff</a>

Remove script language and direction inheritance

---

index.html

This PR fixes #3 by removing the paragraph that recommends that the URL in the canonical identifier resolve the preferred version of the publication.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/28.html" title="Last updated on Aug 10, 2019, 10:13 PM UTC (2b08f50)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/28/8584f7e...2b08f50.html" title="Last updated on Aug 10, 2019, 10:13 PM UTC (2b08f50)">Diff</a>

Remove para about canonical identifier and preferred version

---

index.html

(MIni change.)
The official I18N review claims to prefer the usage of 'well-formed' when referring to conformance to bcp47. Changed this reference.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/37.html" title="Last updated on Aug 21, 2019, 7:55 AM UTC (2612b72)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/37/92c505c...2612b72.html" title="Last updated on Aug 21, 2019, 7:55 AM UTC (2612b72)">Diff</a>

'well-formed' bcp

---

index.html

Fixes #35.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/50.html" title="Last updated on Aug 31, 2019, 3:58 PM UTC (451fb58)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/50/90c168d...451fb58.html" title="Last updated on Aug 31, 2019, 3:58 PM UTC (451fb58)">Diff</a>

Add type property defs to LinkedResource and LocalizableString

---

common/html/bidi-example-table.html
index.html

This PR is fairly large, but the bulk of the changes are purely editorial fixes. These include:
- fixes for language consistency between sections;
- consolidation of prose;
- spelling and grammar fixes;
- diversification of examples
The one change of note is to the required manifest properties. I noticed that we still listed title and reading order, but these are not required in the manifest. They are required in the canonical representation, as they always get compiled if not explicit. I've done my best to make the distinction between the manifest requirements and the WebIDL clear, but comments welcome. (See the changes to 2.2 and 2.3.)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/54.html" title="Last updated on Sep 6, 2019, 11:56 AM UTC (fa54d7d)">Preview</a> | …

Editorial cleanup

---

index.html

Adding the two values mentioned in https://github.com/audiobooks/issues/12 
I am not sure if I needed to add something for the boolean, since these two are the first added to the document. Let me know and I'll correct that as well.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/43.html" title="Last updated on Sep 6, 2019, 3:50 PM UTC (87caf6b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/43/18242ea...87caf6b.html" title="Last updated on Sep 6, 2019, 3:50 PM UTC (87caf6b)">Diff</a>

Adding isFamilyFriendly and Abridged

---

index.html
schema/publication.schema.json

This PR adds boolean to the manifest values types and limits it to `true` or `false`.
It also updates the definition, webidl and schema for the abridged property.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/55.html" title="Last updated on Sep 6, 2019, 5:45 PM UTC (77d2572)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/55/efc5c36...77d2572.html" title="Last updated on Sep 6, 2019, 5:45 PM UTC (77d2572)">Diff</a>

Add boolean value type

---

index.html

One question I had is that there was already an example of `dc:subject` but the note before the example incorrectly suggested `dc` maps to dcterms.
Did we actually want to include a dc element set example, or is my correcting the prefix to `dcterms` fine?
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/59.html" title="Last updated on Sep 15, 2019, 3:18 PM UTC (7790daf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/59/a514e50...7790daf.html" title="Last updated on Sep 15, 2019, 3:18 PM UTC (7790daf)">Diff</a>

Add basic dcterms:conformsTo example

---

index.html

This PR should fix #66. It updates the local language example to also show the global language that is being overridden, so the value of `name` is an array.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/70.html" title="Last updated on Sep 18, 2019, 12:12 AM UTC (1e0fbbf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/70/fc0b219...1e0fbbf.html" title="Last updated on Sep 18, 2019, 12:12 AM UTC (1e0fbbf)">Diff</a>

update local language declaration to include global language

---

index.html

Fixes #67
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/78.html" title="Last updated on Sep 23, 2019, 11:39 PM UTC (e7ff0ed)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/78/1b2c35c...e7ff0ed.html" title="Last updated on Sep 23, 2019, 11:39 PM UTC (e7ff0ed)">Diff</a>

Remove requirement that all URLs dereference

---

index.html

I noticed while looking at #77 that the first bullet in the extension section has become a bit vague now that we've removed web publications. The intro is also pretty terse and probably unnecessary as a separate section.
This PR tries to improve this by merging the intro with the requirements and making the first bullet specifically reference section 2. Together with #77, we'll have requirements on the three major sections of the specification for extensions.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/81.html" title="Last updated on Sep 24, 2019, 5:13 PM UTC (d5f8bf9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/81/1b2c35c...d5f8bf9.html" title="Last updated on Sep 24, 2019, 5:13 PM UTC (d5f8bf9)">Diff</a>

Updates to extension section

---

index.html

An attempt to resolve #63. Requires the profiles use one of the linking methods in the discovery of the manifest.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/77.html" title="Last updated on Sep 25, 2019, 11:43 AM UTC (ac4f1b6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/77/023dcd2...ac4f1b6.html" title="Last updated on Sep 25, 2019, 11:43 AM UTC (ac4f1b6)">Diff</a>

Add manifest linking requirement to the extension requirements

---

index.html

I noticed that we have `type` listed as a required property, but we also assume a default of "CreativeWork" when it's not specified, which sort of undermines it being required.
This PR removes `type` from the required property list and also specifies the default value in the webidl.
This means that only `@context` and `conformsTo` always have to be specified, which seems right as these are keys to knowing you have a pub manifest and what kind. The other key pieces of metadata either have a default or are harvested when not specified.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/91.html" title="Last updated on Oct 1, 2019, 1:13 PM UTC (2cc4995)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/91/35a23c9...2cc4995.html" title="Last …

Remove requirement for type

---

index.html

While toying with my implementation I realized that the exact role of the `null` value for direction and language was not precise, and the necessary steps were missing from the processing steps.
@mattgarrish, there might be some linguistic or editorial clumsiness. Once final, this should be merged into the json-ld-base-direction branch, i.e., into the branch for #92
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/97.html" title="Last updated on Oct 4, 2019, 2:30 PM UTC (e61fbf1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/97/f08d167...e61fbf1.html" title="Last updated on Oct 4, 2019, 2:30 PM UTC (e61fbf1)">Diff</a>

Made some implicit rules on language/direction `null` values explicit

---

index.html

This adds a "List of Requirements" as an additional navigation section, after the table of contents.
I'm intending for this to be a (hopefully) useful tool for reviewing the editor's draft as a part of the ReSpec workflow. I developed this in response to our TPAC F2F, when we talked about extracting the MUSTs/SHOULDs into a spreadsheet, for the creation of test cases.
The added nav list is populated by scraping the specification document's HTML markup.
Each list item is an occurrence of a "MUST" or "SHOULD" RFC 2119 keyword, along with some context.
List item headers link back to the respective section containing the keyword.
The item elements themselves are clickable, and scroll to the reference location in the document.
A "shortcut" button appears next to the ReSpec UI button, to allow …

Add "List of Requirements" to sidebar

---

index.html

I made a mistake with the respec specific classes I used for #79 
The styles for the requirements list are not being applied if the class `remove` is on the reqlist stylesheet include.
This means that the requirements list has unintended numbering, since the stylesheet with the intended styles gets removed right away by ReSpec.
Changing this to `removeOnSave` applies the intended lifecycle for this link element: Not removing right away, but removing when ReSpec exports or finalizes the TR.
***
<a href="https://pr-preview.s3.amazonaws.com/jccr/pub-manifest/pull/99.html" title="Last updated on Oct 7, 2019, 3:35 AM UTC (09b707b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/99/9437d12...jccr:09b707b.html" title="Last updated on Oct 7, 2019, 3:35 AM UTC …

Fix "ReqList" stylesheet include

---

common/js/biblio.js
index.html
schema/publication.schema.json

I have incorporated the usage of the upcoming JSON-LD 1.1 `@direction` (see the adjacent [PR No. 276](https://github.com/w3c/json-ld-syntax/pull/276) in the JSON-LD WG).
To facilitate review, here are the points were the essential changes happened:
- 2.4.4.1, adding direction to Localizable Strings, plus examples
- 2.6 on global and local setting of language & direction
- Modifications in section 4, steps (6), (7c), (9d)
- Added Appendix E
See also #75 for the background and the writeup from the TPAC discussions
Cc: @aphillips, @r12a, I would particularly welcome your check on the examples in 2.4.4.1 and 2.6
Cc: @dauwhe @laudrain @gkellogg
---
Fix #75
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/92.html" title="Last updated on Oct 4, 2019, 2:47 PM UTC …

Settting the base direction

---

index.html

- removal of the separate appendix on json-ld 1.1 dependency
- addition of a note emphasizing this dependency in the text
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/102.html" title="Last updated on Oct 7, 2019, 5:23 PM UTC (6e0a422)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/102/060d46b...6e0a422.html" title="Last updated on Oct 7, 2019, 5:23 PM UTC (6e0a422)">Diff</a>

Final changes, as agreed on the call 2019-10-07

---

schema/publication.schema.json

This got forgotten, but it updates the schema to reflect the actual authoring requirements - context and conformsTo.

Fix required schema properties

---

common/css/common.css
index.html

This PR makes the following changes:
- updates the processing algorithm to split it into more atomic functions where appropriate (makes the main algorithm clearer and also makes it easier for profiles to extend specific functions instead of step numbers).
- updates description and accessibilitySummary to arrays of localizable strings.
- standardizes the name "value category".
- adds a generic object category and updates accessModeSufficient to reference it.
- adds prose for reading systems to inspect reading order for unknown profiles and react accordingly.
It should fix #101 #106 #108 #109 #110 #113 and #115
I'm going to update the experimental processor code next just to make sure I didn't break anything splitting up the algorithm.
***
<a …

Updates to processing algorithm and other fixes

---

index.html

This PR switches the algorithm to insert types during processing so that they can be reliably used as the context for processing terms later on.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/129.html" title="Last updated on Oct 21, 2019, 12:55 PM UTC (bfd51c3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/129/9a5d8d1...bfd51c3.html" title="Last updated on Oct 21, 2019, 12:55 PM UTC (bfd51c3)">Diff</a>

use object type for context

---

index.html

I found a few more issues with the algorithm while updating the test code:
- a couple of steps were referring to incorrect variable names;
- the recursion step in validation checks has to occur before any of the validity checks (except type), as the validity checks have to work from the bottom up. if not, invalid data won't yet have been removed when some tests are run.
- similarly, it's necessary to remove invalid localizable strings before checking, for example, whether an entity has a name, so I had to move it up.
- we weren't checking whether localizable strings have a `value`, so I added that with the language/direction tests
- the absolute url function wasn't checking/returning failures from url parser; I also simplified this a bit as it doesn't need recursion.
- I added some …

Additional algorithm updates

---

index.html

Per #122, this PR adds a recommendation to note the severity of validation errors.
I'm kind of waffling on the wording of this one, so alternatives welcome.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/127.html" title="Last updated on Oct 20, 2019, 3:42 PM UTC (91b12f6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/127/bfdeae3...91b12f6.html" title="Last updated on Oct 20, 2019, 3:42 PM UTC (91b12f6)">Diff</a>

Add recommendation to note severity

---

index.html

Fixes #112 by adding type and id as recommended properties in "2.2 Requirements".
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/119.html" title="Last updated on Oct 18, 2019, 1:05 AM UTC (368270e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/119/07f264d...368270e.html" title="Last updated on Oct 18, 2019, 1:05 AM UTC (368270e)">Diff</a>

add type and id as recommended properties

---

index.html

Fixes #124. Adds warning if canonical id isn't set or is an empty string.
We already have a check for type that generates a warning and adds CreativeWork. I guess that was a leftover from when it was required.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/125.html" title="Last updated on Oct 19, 2019, 9:51 PM UTC (3b3a7c3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/125/a15c211...3b3a7c3.html" title="Last updated on Oct 19, 2019, 9:51 PM UTC (3b3a7c3)">Diff</a>

add canonical id check

---

index.html

These changes are in addition to the ones in PR #131. Breaking them out to make them easier to read, but will merge them before Monday's call.
- restore the restriction on duplicate resources in reading order, but only as recommendation so the entries are not removed;
- remove the restriction against fragment identifiers in the structural relations (toc, pagelist, cover);
- simplify the steps that reference all the unsupported data types for a value (simplifies to "if not a map ..." as the final step always expects a map);
- handle lists of URLs in the URL normalize step;
- warn but don't remove duplicate resources from reading order and resource list;
- remove links that specify relations that have to be in publication bounds from the links section;
- add item["type"] as the context when …

Additional pub resources/algorithm cleanup

---

index.html

A couple of minor issues I spotted wrapping up:
- was missing a continue statement after deleting a link
- there was still a warning for encodingFormat not being set
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/142.html" title="Last updated on Nov 1, 2019, 10:57 PM UTC (c98d034)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/142/c48a055...c98d034.html" title="Last updated on Nov 1, 2019, 10:57 PM UTC (c98d034)">Diff</a>

Final algorithm tweaks

---

index.html

This PR makes the following changes:
- it limits the contents and pagelist relations to one resource
- it adds a step to validate the relation requirements - also includes that covers should have a name and description
- I also moved the structural relations ahead of the informative relations in the spec, as I find it annoying the less important relations are listed first
But I think this needs more work as described in #143.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Nov 3, 2019, 10:44 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service …

enforce rel requirements

---

index.html

Here's an attempt to thread the needle on alternates.
It seems like we have to define at least minimal expectations if we want to still talk about alternate covers, or have alternates for audiobooks. To that end, I explain that we only define the property for use with `encodingFormat`. I've also defined a minimal selection algorithm.
Does this look like it will work?
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/146.html" title="Last updated on Nov 5, 2019, 12:36 PM UTC (312950a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/146/e4a68d7...312950a.html" title="Last updated on Nov 5, 2019, 12:36 PM UTC (312950a)">Diff</a>

possible formulation of alternate

---

index.html

One last validation detail I noticed missing from the algorithm.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/151.html" title="Last updated on Nov 7, 2019, 6:04 PM UTC (4f9f2ff)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/151/809f4d0...4f9f2ff.html" title="Last updated on Nov 7, 2019, 6:04 PM UTC (4f9f2ff)">Diff</a>

add warning if rel not set for links

---

index.html

This PR addresses #155 as follows:
- expands on title and reading order to clarify that user agent data harvesting occurs when not specified
- changes the name of "add html defaults" to "add default values" and makes the html document optional
Making the html doc optional allows, for example, for the title to be generated regardless of whether there is a linking document (i.e., processing falls through to the UA having to generate a title). It also makes the function more versatile in case other situations like this arise where you either get something from the html doc or have to generate.
It also doesn't greatly change what we already had, which is always nice.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/157.html" title="Last updated on Nov 8, 2019, 3:38 PM …

Clarify default value processing

---

index.html

I went back over the specification to double-check recommended practices (not currently caught in the reqlist generator) and found some problematic statements that I've removed/reworded to not be normative, and a few things not accounted for in the algorithm.
- Recommending to use linked records rather than additional properties is probably a bad idea. Technically, it means we should warn about every property not defined by the specification. It also picks a winner when we don't know all the real-world use cases for metadata. For those reasons, I'm suggesting we drop that recommendation with this PR.
- It's pointless to recommend using linked resources for linked records when linked resources are required by the structural properties.
- We recommend the `describedby` relation for …

recommended practices review

---

index.html

This PR moves the introduction that was in the pub manifest section up to the top-level introduction. We originally had an intro per section in wpub when we had three separate parts, but it seems redundant now.
Some of the intro sections have normative statements in them, so I'd still apply the non-normative label on a section-by-section basis.
The terminology and conformance sections are moved out of the intro, as this looks like a common practice in some other specs I looked at.
No prose has been changed.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/162.html" title="Last updated on Nov 11, 2019, 5:00 PM UTC (6deb283)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/162/4f4a366...6deb283.html" title="Last updated on Nov 11, 2019, 5:00 …

Rearrange introduction sections

---

experiments/audiobook/flatland-canonical.json
experiments/audiobook/flatland.json
index.html
schema/link.schema.json

Harmonizes so we don't have two properties for the same purpose with different names and different valid values.
https://github.com/w3c/audiobooks/issues/42
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/164.html" title="Last updated on Nov 13, 2019, 12:51 AM UTC (35cd46f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/164/59baa51...35cd46f.html" title="Last updated on Nov 13, 2019, 12:51 AM UTC (35cd46f)">Diff</a>

switch length to duration for LinkedResource

---

index.html

Whether or not https://github.com/w3c/audiobooks/issues/48 results in a change, profile validation/defaults should be prioritized over the general manifest rules.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/165.html" title="Last updated on Nov 13, 2019, 4:16 PM UTC (aaa8873)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/165/f51698d...aaa8873.html" title="Last updated on Nov 13, 2019, 4:16 PM UTC (aaa8873)">Diff</a>

Prioritize extension validation

---

experiments/audiobook/flatland.json

This is to handle https://github.com/w3c/audiobooks/issues/50. The version in the PR is checked by my "validator" (provided my code is correct:-).
fix https://github.com/w3c/audiobooks/issues/50
I am not sure about the values/meanings of the accessibility term, they should at least be correct... Please check.

Correct flatland manifest

---

index.html

I noticed yesterday with audiobooks that using boolean flags is getting a bit too programming level specific for the algorithms, so I went back to remove them from the manifest rel checks, too.
This PR doesn't change the outcome of the step, but maybe makes it a bit clearer what we're checking for without getting into the details of how to do it.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/167.html" title="Last updated on Nov 16, 2019, 2:04 PM UTC (118b624)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/167/d8d49c4...118b624.html" title="Last updated on Nov 16, 2019, 2:04 PM UTC (118b624)">Diff</a>

get rid of boolean flagging in rel checks

---

index.html

Fixes wcag link and removes unnecessary note as requested in https://github.com/w3c/transitions/issues/190#issuecomment-557687866
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/170.html" title="Last updated on Nov 23, 2019, 1:28 AM UTC (f4e0ce6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/170/d30fe3f...f4e0ce6.html" title="Last updated on Nov 23, 2019, 1:28 AM UTC (f4e0ce6)">Diff</a>

updates per cr transition feedback

---

index.html

As requested in the [transition request comments](https://github.com/w3c/transitions/issues/190#issuecomment-557807881).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/171.html" title="Last updated on Nov 23, 2019, 4:11 PM UTC (779cad5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/171/bad5c66...779cad5.html" title="Last updated on Nov 23, 2019, 4:11 PM UTC (779cad5)">Diff</a>

Update tr/html links to reference whatwg html spec

---

index.html

Although there's no explicit reference to Synchronized Narration in this section, example #6 uses it to show how the 'alternate' property works. This is a correction to the encoding format used in that example, to align with the current draft of Synchronized Narration.
***
<a href="https://pr-preview.s3.amazonaws.com/marisademeglio/pub-manifest/pull/172.html" title="Last updated on Nov 28, 2019, 6:49 PM UTC (41653af)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/172/ae9d535...marisademeglio:41653af.html" title="Last updated on Nov 28, 2019, 6:49 PM UTC (41653af)">Diff</a>

Fix encoding format for "alternate" example

---

index.html

The text should say `publication` and not `manifest`
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/184.html" title="Last updated on Dec 19, 2019, 3:30 PM UTC (cc60a40)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/184/aa1f795...cc60a40.html" title="Last updated on Dec 19, 2019, 3:30 PM UTC (cc60a40)">Diff</a>

Stupid cut-and-paste error on the IANA section

---

index.html

A few minor tweaks:
- adds profile discovery option to toc relation section
- changes remaining algo text to a note
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/185.html" title="Last updated on Jan 7, 2020, 6:01 PM UTC (81526e3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/185/7a93437...81526e3.html" title="Last updated on Jan 7, 2020, 6:01 PM UTC (81526e3)">Diff</a>

Changes to toc discovery

---

index.html

This is relevant to settle: https://github.com/w3c/audiobooks/issues/63.
---
Note that, if merged, the change section should be added. I did not do it here, because it would lead to merge conflicts with #180...
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/183.html" title="Last updated on Jan 27, 2020, 12:05 PM UTC (c047dcb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/183/aa1f795...c047dcb.html" title="Last updated on Jan 27, 2020, 12:05 PM UTC (c047dcb)">Diff</a>

Added an extension point for profiles in the TOC file localization

---

index.html

- took care of https://github.com/w3c/pub-manifest/pull/180#discussion_r357962658 and https://github.com/w3c/pub-manifest/pull/180#discussion_r357962970
- to handle the issue https://github.com/w3c/pub-manifest/pull/180#issuecomment-567124310 I exchanged the word 'exit' in the relevant sentences to 'omit', with a further clarification in the initial note
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/182.html" title="Last updated on Jan 8, 2020, 10:46 AM UTC (463c46f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/182/125f6ac...463c46f.html" title="Last updated on Jan 8, 2020, 10:46 AM UTC (463c46f)">Diff</a>

Minor updates on #180

---

index.html

Fixes #181 as discussed in the issue.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/187.html" title="Last updated on Jan 27, 2020, 5:57 PM UTC (02fbd60)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/187/caac6b9...02fbd60.html" title="Last updated on Jan 27, 2020, 5:57 PM UTC (02fbd60)">Diff</a>

clarify the form of the manifest data is not changeable

---

index.html

This PR fixes #173 by adding a paragraph explaining that the processed table of contents does not have to retain the presentational aspects of the toc.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/190.html" title="Last updated on Jan 27, 2020, 8:11 PM UTC (0916c5b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/190/24ac983...0916c5b.html" title="Last updated on Jan 27, 2020, 8:11 PM UTC (0916c5b)">Diff</a>

presentational aspects of toc lost with processing

---

index.html

This PR fixes #186 and #188 as follows:
- notes that profiles may add additional context URLs
- removes the paragraph about requiring https for schema.org
- adds a general extension point for processing the context by a profile's rules
(I can restore the https bit if you think it's a blocker, but I just don't see the value in it.)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/189.html" title="Last updated on Jan 28, 2020, 11:48 AM UTC (6f24fc8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/189/24ac983...6f24fc8.html" title="Last updated on Jan 28, 2020, 11:48 AM UTC (6f24fc8)">Diff</a>

add extension step for profiles to extend the context

---

index.html

Makes the following changes:
- switch must to should for the doc-toc element being the first in the file.
- note for processing to select the first doc-toc regardless of whether it is hidden
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/191.html" title="Last updated on Jan 27, 2020, 8:07 PM UTC (66fa504)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/191/24ac983...66fa504.html" title="Last updated on Jan 27, 2020, 8:07 PM UTC (66fa504)">Diff</a>

Fixes for #174 and #175

---

index.html

Due to a variety of problems that fragments present (conflicting purposes, inability to duplicate references, no fragments in resource list, etc., see #176), this PR reverts to our previous restriction against using fragments for identifying the table of contents.
Other than preserving some recent clarifications, the prose is set back to what we had in the 2019-09-11 draft.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/192.html" title="Last updated on Jan 28, 2020, 12:57 PM UTC (e946c7b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/192/04f4371...e946c7b.html" title="Last updated on Jan 28, 2020, 12:57 PM UTC (e946c7b)">Diff</a>

disallow fragments for identifying the toc

---

index.html

See https://www.iana.org/assignments/link-relations/link-relations.xhtml
As a consequence, the relevant note has been removed from the text.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/194.html" title="Last updated on Feb 4, 2020, 11:09 AM UTC (6a41ccd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/194/42732b5...6a41ccd.html" title="Last updated on Feb 4, 2020, 11:09 AM UTC (6a41ccd)">Diff</a>

The publication link relation is now registered

---

index.html

This PR fixes #198 by adding back the primary entry page requirements to be a resource and be added to the reading order when one isn't present so that the processing algorithm matches the prose again.
I made some minor changes to the original language, since the concept of the page that links to the manifest being called the "primary entry page" wasn't retained.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/199.html" title="Last updated on Feb 12, 2020, 2:22 PM UTC (65d9188)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/199/8d159b4...65d9188.html" title="Last updated on Feb 12, 2020, 2:22 PM UTC (65d9188)">Diff</a>

add back reading order requirements

---

index.html

Fixes #206 by changing sequence<DOMString> to sequence<object>
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/209.html" title="Last updated on Apr 15, 2020, 3:47 PM UTC (c521560)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/209/3425460...c521560.html" title="Last updated on Apr 15, 2020, 3:47 PM UTC (c521560)">Diff</a>

Fix accessmodesufficient's webidl definition

---

index.html

Fixes #207 by changing the recommendation for a privacy policy and accessibility report to be resources of the publication (i.e., warnings if not) to best practices. This matches their inclusion in the links section in the examples.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/212.html" title="Last updated on Apr 16, 2020, 4:25 PM UTC (a1b2ecd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/212/48dbca5...a1b2ecd.html" title="Last updated on Apr 16, 2020, 4:25 PM UTC (a1b2ecd)">Diff</a>

change resource location text to match examples

---

index.html

Fixes #211 by rewording the data models appendix to focus only on webidl.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/213.html" title="Last updated on Apr 16, 2020, 11:42 AM UTC (16a491e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/213/48dbca5...16a491e.html" title="Last updated on Apr 16, 2020, 11:42 AM UTC (16a491e)">Diff</a>

change the data models appendix to be singular

---

index.html

Here's a weak-kneed attempt to dodge the problem of author-creator equivalency in schema.org. It blames schema.org for the problem, prefers author and generally avoids saying anything normative.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/214.html" title="Last updated on Apr 30, 2020, 9:46 AM UTC (ea0a248)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/214/34cc0a4...ea0a248.html" title="Last updated on Apr 30, 2020, 9:46 AM UTC (ea0a248)">Diff</a>

explain author/creator equivalence problem

---

index.html

Step 11 of the data validation algorithm isn't very clear that it is also where the readingOrder and resource lists are checked for duplicate declarations. This PR just adds a bit of explanation to this effect.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/217.html" title="Last updated on Apr 30, 2020, 5:27 PM UTC (58e22e1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/217/c114a5c...58e22e1.html" title="Last updated on Apr 30, 2020, 5:27 PM UTC (58e22e1)">Diff</a>

clarify where duplicate resources are checked

---

schema/ItemList.schema.json
schema/contributor-object.schema.json
schema/link.schema.json
schema/publication.schema.json

Fixes #218 and fixes #219.
- Allows a single string value for `accessibilityHazard`
- Requires one or more ItemList objects for `accessModeSufficient`

fix schema expected data types

---

schema/context.schema.json
schema/date.schema.json
schema/duration.schema.json
schema/item-lists.schema.json
schema/language.schema.json
schema/link.schema.json
schema/publication.schema.json
schema/strings.schema.json
schema/urls.schema.json

Fixes the following:
- adds validation for language and direction in the manifest @context
- allows more than one url for address
- fixes alternate so that mixes of strings and linkedresource objects are allowed in the array, as well as allow a single string or linkedresource object as the value;
- also atomizes some tests to reduce future maintenance in other schemas
Fixes #221, fixes #222, and fixes #223

Schema data type fixes

---

schema/module/ItemList.schema.json
schema/module/context.schema.json
schema/module/contributor.schema.json
schema/module/item-lists.schema.json
schema/module/link.schema.json
schema/module/localizable-object.schema.json
schema/module/localizable.schema.json
schema/module/strings.schema.json
schema/module/urls.schema.json
schema/publication.schema.json

A couple of additional things I've fixed in the schemas;
- We were using `uniqueItems: true` inconsistently and in many places where the specification says nothing about the need for uniqueness (even if it makes intuitive sense). You can declare a `type` more than once, for example, without negative effect. I'd suggest we leave messages about duplication for a full-fledged validator to handle, as these shouldn't be errors but more along the lines of epubcheck's info messages (best practices). The only required uniqueness is within `resources`, `readingOrder` and `links` and that check remains in the resource.categorization.schema.json file.
- I replaced two additional regexes for duration/language checking with a references to the patterns I broke out earlier.

Schemas fixes

---

index.html
schema/README.md
schema/module/ItemList.schema.json
schema/module/bcp.schema.json
schema/module/context.schema.json
schema/module/contributor-object.schema.json
schema/module/contributor.schema.json
schema/module/date.schema.json
schema/module/duration.schema.json
schema/module/item-lists.schema.json
schema/module/language.schema.json
schema/module/link.schema.json
schema/module/localizable-object.schema.json
schema/module/localizable.schema.json
schema/module/resource.categorization.schema.json
schema/module/strings.schema.json
schema/module/url.schema.json
schema/module/urls.schema.json
schema/publication.schema.json

As [resolved on the telecon today](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2020/2020-07-27-pwg), updating the URLs to w3c addresses to fix #226.
Before merging, though, we'll need to make sure the redirects are up and running.
Will open a similar PR for audiobooks shortly.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/228.html" title="Last updated on Jul 29, 2020, 2:12 PM UTC (30a6939)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/228/a896d5f...30a6939.html" title="Last updated on Jul 29, 2020, 2:12 PM UTC (30a6939)">Diff</a>

Update schema urls to use w3c address

---

common/js/biblio.js
index.html

This PR updates the references to ISO 8601 for duration values to the new Part 1 version of the standard released last year.
Fixes https://github.com/w3c/audiobooks/issues/65 originally raised in the Audiobooks tracker.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/231.html" title="Last updated on Sep 4, 2020, 1:52 PM UTC (1a2db32)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/231/2bd587f...1a2db32.html" title="Last updated on Sep 4, 2020, 1:52 PM UTC (1a2db32)">Diff</a>

switch iso8601 references to iso8601-1

---

errata/errata.css
errata/index.html
index.html

Added an errata management page and a reference to it from index. This will be necessary for the Rec phase
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/230.html" title="Last updated on Sep 4, 2020, 11:33 AM UTC (6ae7fb4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/230/2bd587f...6ae7fb4.html" title="Last updated on Sep 4, 2020, 11:33 AM UTC (6ae7fb4)">Diff</a>

Added the errata management and reference

---

index.html

I believe it should be `@context`.
***
<a href="https://pr-preview.s3.amazonaws.com/naglis/pub-manifest/pull/232.html" title="Last updated on Sep 10, 2020, 9:05 PM UTC (a1512d6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/232/50cbb97...naglis:a1512d6.html" title="Last updated on Sep 10, 2020, 9:05 PM UTC (a1512d6)">Diff</a>

Fix map key

---

index.html

From the context (`normalized` should be a map here), I think it should be `normalized`, not `item`.
***
<a href="https://pr-preview.s3.amazonaws.com/naglis/pub-manifest/pull/233.html" title="Last updated on Sep 10, 2020, 11:54 PM UTC (a8255c7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/233/50cbb97...naglis:a8255c7.html" title="Last updated on Sep 10, 2020, 11:54 PM UTC (a8255c7)">Diff</a>

Fix to use correct variable name

---

index.html

At 7.4.1 step 9.a.i, if `normalized` is a list containing `item` map, e.g.:
```json
[
{
"type": [
"Person"
],
"name": "Herman Melville"
}
]
```
it seems that context for the recursive normalize data call should be `item["type"]`, not `keyValue["item"]`. In this case, context would be `Person`.
Same applies for step 9.b.i.
It appears `item["type"]` is being used in the reference implementation:
https://github.com/w3c/pub-manifest/blob/9a17073f65c5bae1e120933a9676250016b70148/experiments/manifest-to-internal-processor/manifestProcessor.js#L624
***
<a href="https://pr-preview.s3.amazonaws.com/naglis/pub-manifest/pull/234.html" title="Last updated on Sep 12, 2020, 10:41 PM UTC (3b6fe5a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/234/9a17073...naglis:3b6fe5a.ht …

Fix variable in recursive normalization

---

index.html

Similar to #233, I think it should be `value["type"]` here, instead of `item["type"]`.
***
<a href="https://pr-preview.s3.amazonaws.com/naglis/pub-manifest/pull/239.html" title="Last updated on Sep 25, 2020, 11:42 AM UTC (63cfb6f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/239/1972c1f...naglis:63cfb6f.html" title="Last updated on Sep 25, 2020, 11:42 AM UTC (63cfb6f)">Diff</a>

Fix variable name

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/naglis/pub-manifest/pull/240.html" title="Last updated on Sep 26, 2020, 12:37 AM UTC (e5e3969)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/240/1972c1f...naglis:e5e3969.html" title="Last updated on Sep 26, 2020, 12:37 AM UTC (e5e3969)">Diff</a>

Fix typo in key name

---

index.html
snapshot/index.html

This fixes #244 by adding a parenthetical to the note to explain why the example text differs. It also adds the `bdo` tag to the REC snapshot to fix the rendering.
Note that the editor's draft will still strip the `bdo` tag, so to preview the fully-updated section, please see the snapshot: https://raw.githack.com/w3c/pub-manifest/editorial/text-dir/snapshot/index.html#example-2-set-the-language-and-the-base-direction-of-a-string
Let me know if the added para can use any improvement.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/245.html" title="Last updated on Nov 5, 2020, 1:37 PM UTC (fe3102c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/245/b5c50f7...fe3102c.html" title="Last updated on Nov 5, 2020, 1:37 PM UTC (fe3102c)">Diff</a>

Fix bidi example

---

schema/module/progression.schema.json
schema/publication.schema.json

The term `readingProgression` was missing from the JSON Schema.
Fix #251
Cc: @MurakamiShinyu

Adding reading progression to schema

---

index.html

Fixes the broken link issue reported in #255 and #247 
Fixes #247
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/256.html" title="Last updated on Aug 4, 2023, 5:15 PM UTC (610133e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/256/69eb16e...610133e.html" title="Last updated on Aug 4, 2023, 5:15 PM UTC (610133e)">Diff</a>

Fix changed infra link to json parsing

---

index.html

Here dot notation is used, however bracket notation is used elsewhere throughout the document, so I think it is worth to make it consistent.
Fixes #260 
***
<a href="https://pr-preview.s3.amazonaws.com/naglis/pub-manifest/pull/242.html" title="Last updated on Feb 4, 2021, 3:28 PM UTC (c04e298)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/242/f63fe7c...naglis:c04e298.html" title="Last updated on Feb 4, 2021, 3:28 PM UTC (c04e298)">Diff</a>

Unify map key syntax
