common/js/biblio.js
index.html

Propose changes in section 2.1.3
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/36.html" title="Last updated on Aug 20, 2019, 11:00 AM UTC (03396ff)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/36/a48e4d1...03396ff.html" title="Last updated on Aug 20, 2019, 11:00 AM UTC (03396ff)">Diff</a>

Re-writing the "shape" part

---

index.html
schema/contributor-object.schema.json

Fixes #41.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/49.html" title="Last updated on Aug 31, 2019, 11:18 AM UTC (13127da)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/49/0e85b58...13127da.html" title="Last updated on Aug 31, 2019, 11:18 AM UTC (13127da)">Diff</a>

Add identifier property to CreatorInfo

---

index.html
schema/publication.schema.json

Fixes #48.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/52.html" title="Last updated on Sep 2, 2019, 12:59 PM UTC (a089b21)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/52/356247f...a089b21.html" title="Last updated on Sep 2, 2019, 12:59 PM UTC (a089b21)">Diff</a>

Remove the inDirection property

---

index.html

May not stand up to review, but here's some starter prose.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/53.html" title="Last updated on Sep 4, 2019, 3:50 PM UTC (b0c2959)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/53/356247f...b0c2959.html" title="Last updated on Sep 4, 2019, 3:50 PM UTC (b0c2959)">Diff</a>

Add security and privacy considerations

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/71.html" title="Last updated on Sep 18, 2019, 12:08 AM UTC (a062210)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/71/009b155...a062210.html" title="Last updated on Sep 18, 2019, 12:08 AM UTC (a062210)">Diff</a>

format examples

---

index.html

This PR fixes #60, #62 and #65 by making the following changes:
- it adds a validation check that properties have their expected value types
- it adds definitions for validation and fatal errors and updates algorithm to return failures
- it adds a statement that invalid values should be omitted (we don't need to say to remove the values anymore within the algorithm, so some checks have been modified accordingly)
- it adds a statement that errors should be presented
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/68.html" title="Last updated on Sep 18, 2019, 11:28 AM UTC (20ca22c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/68/fc0b219...20ca22c.html" title="Last updated on Sep 18, 2019, 11:28 AM UTC (20ca22c)">Diff</a>

Updates to processing algorithm

---

index.html

Fixes #80
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/82.html" title="Last updated on Sep 24, 2019, 6:18 PM UTC (e2f5f2d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/82/931f377...e2f5f2d.html" title="Last updated on Sep 24, 2019, 6:18 PM UTC (e2f5f2d)">Diff</a>

Update identifiers description

---

index.html

Fixes #120 and #121 as noted in those issues.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/126.html" title="Last updated on Oct 19, 2019, 10:33 PM UTC (01161b3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/126/a15c211...01161b3.html" title="Last updated on Oct 19, 2019, 10:33 PM UTC (01161b3)">Diff</a>

Clarify validation steps

---

index.html

Fixes #114. This algorithm was already pretty good, but added links and did some minor tweaks.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/123.html" title="Last updated on Oct 19, 2019, 9:04 PM UTC (9021109)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/123/a15c211...9021109.html" title="Last updated on Oct 19, 2019, 9:04 PM UTC (9021109)">Diff</a>

Update toc processing

---

experiments/manifest-to-internal-processor/manifest.json
experiments/manifest-to-internal-processor/manifestProcessor.js
experiments/manifest-to-internal-processor/test.html

No claims of elegance or comprehensiveness of validity checks, but here's the code I've been tinkering with to test the processing algorithm. Includes the clarification I made in https://github.com/w3c/pub-manifest/issues/109#issuecomment-541412866 but doesn't address the redundancies and missed checks that still need to be looked at.
Needs to be run from localhost or off a server. You can maybe run locally if you put the manifest in the script tag, but I have a feeling the URLs will all be invalid since we require http(s).

experimental processor

---

index.html

Does this strike you as sufficient @iherman ?
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/147.html" title="Last updated on Nov 5, 2019, 12:53 PM UTC (d5e1e01)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/147/e4a68d7...d5e1e01.html" title="Last updated on Nov 5, 2019, 12:53 PM UTC (d5e1e01)">Diff</a>

add note about non-validation of prefixes

---

index.html

Fixes #149
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/150.html" title="Last updated on Nov 6, 2019, 3:00 PM UTC (8580b3d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/150/07673e3...8580b3d.html" title="Last updated on Nov 6, 2019, 3:00 PM UTC (8580b3d)">Diff</a>

delete statement about retaining entity properties

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/153.html" title="Last updated on Nov 8, 2019, 1:16 PM UTC (337d1db)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/153/0d4a8f7...337d1db.html" title="Last updated on Nov 8, 2019, 1:16 PM UTC (337d1db)">Diff</a>

Mini mistake in the structural resources' check

---

index.html

Added a section on the `publication` link; to be submitted for registration.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/156.html" title="Last updated on Nov 8, 2019, 3:11 PM UTC (5b9255e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/156/1ea7e7d...5b9255e.html" title="Last updated on Nov 8, 2019, 3:11 PM UTC (5b9255e)">Diff</a>

Added a section on IANA

---

index.html

Fixes #152
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/158.html" title="Last updated on Nov 8, 2019, 5:18 PM UTC (10a2a92)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/158/206c10a...10a2a92.html" title="Last updated on Nov 8, 2019, 5:18 PM UTC (10a2a92)">Diff</a>

Fixes for issue #152

---

index.html

All minor stuff. Will merge tomorrow.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/159.html" title="Last updated on Nov 9, 2019, 12:03 AM UTC (6ec879d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/159/c715fde...6ec879d.html" title="Last updated on Nov 9, 2019, 12:03 AM UTC (6ec879d)">Diff</a>

proofread of processing algorithm

---

index.html

This PR adds a spot for a profile to call new primary processing steps/functions.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/163.html" title="Last updated on Nov 12, 2019, 3:14 PM UTC (1763bcf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/163/0364c4f...1763bcf.html" title="Last updated on Nov 12, 2019, 3:14 PM UTC (1763bcf)">Diff</a>

add extension step to primary algorithm

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/168.html" title="Last updated on Nov 19, 2019, 10:33 AM UTC (1ae6e70)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/168/3874d2b...1ae6e70.html" title="Last updated on Nov 19, 2019, 10:33 AM UTC (1ae6e70)">Diff</a>

Added crEnd and implemenrationReportURI to respec

---

index.html

We had an invalid JSON in the example 13...

Missing comma in a JSON example

---

.travis.yml

Following https://github.com/w3c/echidna/wiki/CR-publication-workflow

Update .travis.yml for editorial CR updates

---

index.html

This PR addresses the issues noted in #179 as well as the rel tokenizing issues in #177.
@iherman I'm not sure if the note about the event model captures what you wanted or not, so feel free to modify if not.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/180.html" title="Last updated on Jan 27, 2020, 2:16 PM UTC (910b47c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/180/a6b77a8...910b47c.html" title="Last updated on Jan 27, 2020, 2:16 PM UTC (910b47c)">Diff</a>

Clarifications to the table of contents algorithm

---

index.html

Fixes #196
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/197.html" title="Last updated on Feb 5, 2020, 11:48 PM UTC (2be8825)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/197/4d26f8b...2be8825.html" title="Last updated on Feb 5, 2020, 11:48 PM UTC (2be8825)">Diff</a>

clarify that rel values are case insensitive

---

index.html

Fixes #195
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/200.html" title="Last updated on Feb 11, 2020, 3:17 PM UTC (dc5e36f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/200/8d159b4...dc5e36f.html" title="Last updated on Feb 11, 2020, 3:17 PM UTC (dc5e36f)">Diff</a>

add null to current_toc_branch name test

---

index.html

Fixes #205
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/208.html" title="Last updated on Apr 15, 2020, 3:00 PM UTC (3425460)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/208/b460c7b...3425460.html" title="Last updated on Apr 15, 2020, 3:00 PM UTC (3425460)">Diff</a>

Remove array from localizablestring definition

---

index.html

Updated to the new version, and added a prEnd (this may have to be updated)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/236.html" title="Last updated on Sep 16, 2020, 9:13 AM UTC (d95cab1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/236/74e1d9e...d95cab1.html" title="Last updated on Sep 16, 2020, 9:13 AM UTC (d95cab1)">Diff</a>

Changed respec reference

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/237.html" title="Last updated on Sep 16, 2020, 1:45 PM UTC (2e79f98)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/237/f8a2772...2e79f98.html" title="Last updated on Sep 16, 2020, 1:45 PM UTC (2e79f98)">Diff</a>

Added the statement on new features into the status section

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/naglis/pub-manifest/pull/238.html" title="Last updated on Sep 18, 2020, 8:22 PM UTC (8f49ff6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/238/1972c1f...naglis:8f49ff6.html" title="Last updated on Sep 18, 2020, 8:22 PM UTC (8f49ff6)">Diff</a>

Remove incorrect link URL

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/261.html" title="Last updated on Aug 8, 2023, 2:59 PM UTC (3ceb194)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/261/69eb16e...3ceb194.html" title="Last updated on Aug 8, 2023, 2:59 PM UTC (3ceb194)">Diff</a>

Update working group name and mail list

---

index.html

Fixes #246
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/259.html" title="Last updated on Aug 4, 2023, 5:22 PM UTC (af20582)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/259/69eb16e...af20582.html" title="Last updated on Aug 4, 2023, 5:22 PM UTC (af20582)">Diff</a>

Minor typo fixes

---

index.html

s/readingDirection/readingProgression/
Fixes #250
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/258.html" title="Last updated on Aug 4, 2023, 5:02 PM UTC (96a2391)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/258/69eb16e...96a2391.html" title="Last updated on Aug 4, 2023, 5:02 PM UTC (96a2391)">Diff</a>

Fix incorrect variable name

---

index.html

s/chater/chapter/
Fixes #253
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/257.html" title="Last updated on Aug 4, 2023, 4:56 PM UTC (adcff1f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/257/69eb16e...adcff1f.html" title="Last updated on Aug 4, 2023, 4:56 PM UTC (adcff1f)">Diff</a>

Fix typo in example
